.PHONY: clean All

All:
	@echo "----------Building project:[ UOCAirways - Debug ]----------"
	@cd "UOCAirways" && "$(MAKE)" -f  "UOCAirways.mk"
clean:
	@echo "----------Cleaning project:[ UOCAirways - Debug ]----------"
	@cd "UOCAirways" && "$(MAKE)" -f  "UOCAirways.mk" clean
