.PHONY: clean All

All:
	@echo "----------Building project:[ UOCinfection - Debug ]----------"
	@cd "UOCinfection" && "$(MAKE)" -f  "UOCinfection.mk"
clean:
	@echo "----------Cleaning project:[ UOCinfection - Debug ]----------"
	@cd "UOCinfection" && "$(MAKE)" -f  "UOCinfection.mk" clean
