.PHONY: clean All

All:
	@echo "----------Building project:[ pac1 - Debug ]----------"
	@cd "pac1" && "$(MAKE)" -f  "pac1.mk"
clean:
	@echo "----------Cleaning project:[ pac1 - Debug ]----------"
	@cd "pac1" && "$(MAKE)" -f  "pac1.mk" clean
