.PHONY: clean All

All:
	@echo "----------Building project:[ PAC3 - Debug ]----------"
	@cd "PAC3" && "$(MAKE)" -f  "PAC3.mk"
clean:
	@echo "----------Cleaning project:[ PAC3 - Debug ]----------"
	@cd "PAC3" && "$(MAKE)" -f  "PAC3.mk" clean
