.PHONY: clean All

All:
	@echo "----------Building project:[ PAC5 - Debug ]----------"
	@cd "PAC5" && "$(MAKE)" -f  "PAC5.mk"
clean:
	@echo "----------Cleaning project:[ PAC5 - Debug ]----------"
	@cd "PAC5" && "$(MAKE)" -f  "PAC5.mk" clean
