.PHONY: clean All

All:
	@echo "----------Building project:[ PAC8 - Debug ]----------"
	@cd "PAC8" && "$(MAKE)" -f  "PAC8.mk"
clean:
	@echo "----------Cleaning project:[ PAC8 - Debug ]----------"
	@cd "PAC8" && "$(MAKE)" -f  "PAC8.mk" clean
