.PHONY: clean All

All:
	@echo "----------Building project:[ Planes - Debug ]----------"
	@cd "Planes" && "$(MAKE)" -f  "Planes.mk"
clean:
	@echo "----------Cleaning project:[ Planes - Debug ]----------"
	@cd "Planes" && "$(MAKE)" -f  "Planes.mk" clean
