.PHONY: clean All

All:
	@echo "----------Building project:[ pac2 - Debug ]----------"
	@cd "pac2" && "$(MAKE)" -f  "pac2.mk"
clean:
	@echo "----------Cleaning project:[ pac2 - Debug ]----------"
	@cd "pac2" && "$(MAKE)" -f  "pac2.mk" clean
