.PHONY: clean All

All:
	@echo "----------Building project:[ PAC4 - Debug ]----------"
	@cd "PAC4" && "$(MAKE)" -f  "PAC4.mk"
clean:
	@echo "----------Cleaning project:[ PAC4 - Debug ]----------"
	@cd "PAC4" && "$(MAKE)" -f  "PAC4.mk" clean
