.PHONY: clean All

All:
	@echo "----------Building project:[ PAC6 - Debug ]----------"
	@cd "PAC6" && "$(MAKE)" -f  "PAC6.mk"
clean:
	@echo "----------Cleaning project:[ PAC6 - Debug ]----------"
	@cd "PAC6" && "$(MAKE)" -f  "PAC6.mk" clean
